apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: python:3.10-slim
        command: ["/bin/bash", "-c"]
        args:
          - |
            apt-get update && apt-get install -y git &&
            git clone https://github.com/thethomasam/reverse-proxy-tunnel.git  &&
            cd /reverse-proxy-tunnel &&
            pip install -r requirements.txt &&
            python /Backend/backend.py
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend  # Matches the labels in the Deployment
  ports:
    - protocol: TCP
      port: 80           # Port exposed by the Service
      targetPort: 8080   # Port exposed by the container (from the Deployment)
  type: LoadBalancer
