apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: aiml-engineering
  name: backend
  labels:
    app: test-backend
    service: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-backend
      service: backend
  template:
    metadata:
      labels:
        app: test-backend
        service: backend
    spec:
      containers:
      - name: backend
        image: docker.io/thesamthomas77/backend-env:v3
        command: ["/bin/bash", "-c"]
        args:
            - |
              apt-get update && apt-get install -y git &&          
              git clone https://github.com/thethomasam/reverse-proxy-tunnel.git &&
              cd reverse-proxy-tunnel &&
              python Backend/backend.py
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  # namespace: aiml-engineering
  name: backend-service 
  labels:
    app: test-backend
    service: backend
spec:
  type: ClusterIP
  selector:
    app: test-backend
    service: backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  sessionAffinity: None
